### ISSUE TITLE
How do I Name Things?

### ISSUE THREAD

**Issue by ghost** [cmneal26/Tech-Writing-Project#2]
Your project seems cool, and I'd like to contribute. However, I have a couple questions.

 - **Branch Naming Conventions**: If I clone this repository to my local machine, and create a new branch, how should I name that branch?
 
 - **Commit Naming Conventions**: When I commit my work on my local newly created branch, is there any format you'd like me to follow for the messages I attach to each commit?

**Comment by twalker** [comment]
I think you mean, **our** project, I just got us kicked off with a starting point.

> Branch Naming Conventions

Just my opinion, but I prefer short, semantic, and action oriented in kebab-case.
Examples:
```
fix-header-wrap
remove-unneeded-pages
add-layout-styling
```

> Commit Naming Conventions: 

Personally, I think a good commit message is:

* No longer than 80 characters
* Written for humans instead of machines
* Succinctly describes what the changes achieve at a high level
* Bonus: Mentions specific issues at the end: "closes #123"
