### ISSUE TITLE
Do I need Any Special Format When I Open A Pull Request?

### ISSUE THREAD

**Issue by ghost** [cmneal26/Tech-Writing-Project#5]
I opened my first pull request here: https://github.com/cmneal26/Tech-Writing-Project/pull/3

However, I wasn't sure how I should describe my changes when I opened it.

Is there some sort of format you want me to use for the pull request message, or is anything fine?

**Comment by twalker** [comment]
Great idea. Providing context for changes are important so that reviewers aren't asking themselves, "What is this doing and why?". One of us could open a pull request containing a template with a proposed format. I can put up a PR later today unless you beat me to it--you're knocking things out left and right 😄 

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository

**Comment by ghost** [comment]
@cmneal26 

That would be great if you could show us a PR with a reasonable format!
